version: '3.8'

services:
  web:
    image: saiffulllah/framerate-store:latest
    container_name: framerate-store-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped