version: '3.8'

services:
  web-jenkins:
    # THIS IS THE FIX: We use your custom built image containing the CSS/JS!
    image: saiffulllah/framerate-store:latest
    container_name: framerate-store-jenkins-web
    ports:
      # Expose on 3001 so it doesn't conflict with your live app on 3000
      - "3001:3000"
    env_file:
      - .env
    restart: unless-stopped